language: cpp
compiler:
  - clang
  - gcc
before_script:
# gcc 4.7 and boost 1.54
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo add-apt-repository ppa:boost-latest/ppa --yes
  - sudo apt-get update -qq
  - sudo apt-get install git cmake gcc-4.7 g++-4.7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.7
  - sudo update-alternatives --config gcc
  - sudo apt-get install libboost1.54-dev
  - sudo apt-get install libboost-filesystem1.54-dev libboost-regex1.54-dev libboost-system1.54-dev libboost-thread1.54-dev
# close openimageio and build/install
  - git clone https://github.com/OpenImageIO/oiio.git --branch RB-1.4 --depth 1
  - cd oiio
  - git apply ../oiio.patch
  - sudo make USE_QT=0 USE_OPENGL=0 USE_PYTHON=0 USE_FIELD3D=0 USE_OPENJPEG=0 USE_GIF=0 USE_OCIO=0 USE_OPENSSL=0 USE_LIBRAW=0 NOTHREADS=0 OIIO_BUILD_TOOLS=0 OIIO_BUILD_TESTS=0 -e dist_dir= INSTALLDIR=/usr
  - cd ..
script:
  - cmake ./
  - make

